name: Publish JSR package
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Change directory
        run: cd ./apps/cli

      - name: Publish package
        run: npx jsr publish
