name: Publish npm package
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # Run this only when the package.json file changes
    paths:
      - 'apps/cli/package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          cd ./apps/cli
          npm install

      - name: Publish package
        run: |
          cd ./apps/cli
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
