name: PR Check

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies and build
        run: |
          cd ./apps/cli
          pnpm i
          pnpm build

      - uses: JS-DevTools/npm-publish@v3
        with:
          package: ./apps/cli
          token: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        run: |
          cd ./apps/cli
          pnpm test

      - name: Build docs
        run: |
          cd ./apps/docs
          pnpm build
